/**
 * Alvo ID API
 * API desenvolvida para realizar as validações, autenticações e gerenciamento de usuários, células e eventos O Alvo Church.
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ErrorResponse { 
    message?: boolean;
    error?: string;
}