/**
 * Alvo ID API
 * API desenvolvida para realizar as validações, autenticações e gerenciamento de usuários, células e eventos O Alvo Church.
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Event } from './event';

export interface Payment { 
    method: Payment.MethodEnum;
    detail?: string;
    cardFlag?: Payment.CardFlagEnum;
    bank?: string;
    value: number;
    status: string;
    idUser: string;
    area?: string;
    cell?: string;
    event: Event;
    attendant: string;
    creatAt?: Date;
    update?: Date;
}
export namespace Payment {
    export type MethodEnum = 'PIX' | 'DINHEIRO' | 'CREDITO' | 'DEBITO' | 'CARTEIRA DIGITAL';
    export const MethodEnum = {
        PIX: 'PIX' as MethodEnum,
        DINHEIRO: 'DINHEIRO' as MethodEnum,
        CREDITO: 'CREDITO' as MethodEnum,
        DEBITO: 'DEBITO' as MethodEnum,
        CARTEIRADIGITAL: 'CARTEIRA DIGITAL' as MethodEnum
    };
    export type CardFlagEnum = 'VISA' | 'MASTERCARD' | 'ELO' | 'HIPERCARD' | 'AMEX';
    export const CardFlagEnum = {
        VISA: 'VISA' as CardFlagEnum,
        MASTERCARD: 'MASTERCARD' as CardFlagEnum,
        ELO: 'ELO' as CardFlagEnum,
        HIPERCARD: 'HIPERCARD' as CardFlagEnum,
        AMEX: 'AMEX' as CardFlagEnum
    };
}