export * from './auth.service';
import { AuthService } from './auth.service';
export * from './enrollment.service';
import { EnrollmentService } from './enrollment.service';
export * from './event.service';
import { EventService } from './event.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './validate.service';
import { ValidateService } from './validate.service';
export const APIS = [AuthService, EnrollmentService, EventService, PaymentService, UserService, ValidateService];
